### ISSUE TITLE
changing color of font for spotify module

### ISSUE THREAD

**Issue by dmbr0** [NeshHari/XMonad#1] opened 2023-01-23 07:54 UTC
Thank you for this! has been a great help getting my laptop setup. 

I am using a slightly different setup and color scheme. My spotify polybar module font color is black and my bar is almost black. I have everything setup exactly as it is in the repository but I cannot seem to figure out where the font colors are for that module. Any guidance would be much appreciated. Thanks!

**Comment by NeshHari** [comment] 2023-01-23 11:35
Thanks for reaching out. Most polybar colors are imported from catppuccin.ini by placing "include-file = ./catppuccin.ini".  However, I did not specifiy any catppuccin colors as the font defaults to ${colors.text} for my setup since that's defined in [bar/main] foreground = ${colors.text}. So if you don't specify any colors, it will use the default set for your bar. To change the color for the fonts for only the spotify module, please specify as follows:

[module/spotify]
...
format-foreground = ${colors.mauve} <-- for text only (if using catppuccin.ini or you can specify any valid hex e.g. "#ffffff")
format-prefix-foreground = #1DB954 <-- for logo only (note: this is not a catppuccin color but the official spotify logo color)
...

You can also replace "mauve" with any color variables found in catppuccin.ini. Hope this helps :)

**Comment by dmbr0** [comment] 2023-01-24 15:15
I have set the colors in the [module/spotify] and I am still having the same problem.
only the color of the spotify logo is changing. when I change the foreground color in [bar/main] it changes but it also changes the text color of the other modules.

**Comment by NeshHari** [comment] 2023-01-24 15:57
Please paste your full config.ini here or a pastebin link or something.

**Comment by NeshHari** [comment] 2023-02-02 07:37
likely a user-specific integration conflict. cant reproduce. closing.

**Closed** 2023-02-02 07:38 UTC
